### ISSUE TITLE
100% CPU usage on Windows

### ISSUE THREAD

**Issue by acty-yoshida** [treasure-data/serverengine#76]
I found this problem using fluentd in Windows Server 2012R2.
The debugging results, I think following point is the cause of problem.

```
class MultiWorkerServer < Server
    def run
      while true ### loop very high frequency
        num_alive = keepalive_workers
        break if num_alive == 0
        wait_tick  ### no wait at windows os
      end
    end
end
```

* MultiSpawnServer.wait_tick calls ProcessManager.tick.
  I think there are some problem in ProcessManager.tick method on Windows.

**Comment by tagomoris** [comment]
Hmm, this `if` should be out of `unless ServerEngine.windows?`:
https://github.com/treasure-data/serverengine/blob/master/lib/serverengine/process_manager.rb#L247

**Comment by acty-yoshida** [comment]
I think so.
I've tried it in my environment. That's works fine.

```
def tick(blocking_timeout=0)
  if @closed
    raise AlreadyClosedError.new
  end

  # move 
  if @rpipes.empty?
    sleep blocking_timeout if blocking_timeout > 0
    return nil
  end

  time ||= Time.now

  unless ServerEngine.windows?
    # heartbeat is not supported on Windows platform.

    ...
```

**Comment by tagomoris** [comment]
@acty-yoshida thank you to try it! I pushed #77.
