### ISSUE TITLE
linux: allow configurable socketmanager path

### ISSUE THREAD

**Issue by joelvanderkwaak** [treasure-data/serverengine#86]
Currently hardwired:

https://github.com/treasure-data/serverengine/blob/master/lib/serverengine/socket_manager.rb#L71

 '/tmp/SERVERENGINE_SOCKETMANAGER_' + Time.now.to_s.gsub(' ', '') + '_' + Process.pid.to_s

which can cause problems if /tmp is periodically cleaned up

I encountered this using fluentd, so arguably it's a issue there, rather than serverengine:

https://github.com/fluent/fluentd/blob/master/lib/fluent/supervisor.rb#L57

**Comment by tagomoris** [comment]
@repeatedly It seems better to have an ENV variable to specify `SERVERENGINE_SOCKETMANAGER_SOCK_DIR` (default `/tmp`).

**Comment by joelvanderkwaak** [comment]
I think that would work, thanks.

**Comment by repeatedly** [comment]
Release v2.0.5

**Comment by DarkLordVicky** [comment]
Hi 
I am getting this error while running fluentd on docker swarm . The process is run by root not sure what permissions its looking for : 

 Unexpected error Permission denied - connect(2) for /tmp/SERVERENGINE_SOCKETMANAGER_2020-02-13T06:04:46Z_6

following is my socket_manager.rb

          end
        else
          '/tmp/SERVERENGINE_SOCKETMANAGER_' + Time.now.to_s.gsub(' ', '') + '_' + Process.pid.to_s
          base_dir = (ENV['SERVERENGINE_SOCKETMANAGER_SOCK_DIR'] || '/tmp')
          File.join(base_dir, 'SERVERENGINE_SOCKETMANAGER_' + Time.now.utc.iso8601 + '_' + Process.pid.to_s)
        end

**Comment by ymypby** [comment]
@DarkLordVicky I meet the same error.Have you solved it
