### ISSUE TITLE
Windows 10: Unexpected error unsupported signal SIGQUIT

### ISSUE THREAD

**Issue by adback03** [treasure-data/serverengine#89]
As the title shows, I am receiving an error when trying to run on Windows 10:

`Unexpected error unsupported signal SIGQUIT`

Any ideas? Serverengine is getting used by Sneakers (ruby gem), and Serverengine is throwing this error.

**Comment by adback03** [comment]
I found a similar error occurred in this build as well on appveyor: https://ci.appveyor.com/project/fluent/fluentd/build/2345/job/mgy36d6xqqlye4bt

**Comment by repeatedly** [comment]
I saw actual report and it uses older serverengine.
This error should not happen with latest version.
